export const navLinks = [
  {
    id: 1,
    name: "Home",
    href: "#home",
  },
  {
    id: 2,
    name: "About",
    href: "#about",
  },
  {
    id: 3,
    name: "Projects",
    href: "#projects",
  },
  {
    id: 4,
    name: "Work",
    href: "#work",
  },
  {
    id: 5,
    name: "Contact",
    href: "#contact",
  },
];

export const workTimelineItems = [
  {
    id: 1,
    title: "Full Stack Developer",
    location: "Saint Paul, MN",
    company: "Ecolab",
    buttonText: "Details",
    date: "Aug 2024 - Present",
    icon: "work",
    hovercolor: "#5271CA",
    color: "green",
    description: [
      "Angular",
      "TypeScript",
      "C# .NET",
      "Snowflake",
      "Azure",
      "REST API",
      "Git",
    ],
  },
  {
    id: 2,
    title: "Machine Learning Course Assistant",
    location: "Rochester, NY",
    company: "Rochester Institute of Technology",
    buttonText: "Details",
    date: "Jan 2024 - Aug 2024",
    icon: "work",
    hovercolor: "#e37e2b",
    color: "red",
    description: [
      "Python",
      "PyTorch",
      "TensorFlow",
      "Linux",
      "Git",
      "Jupyter Notebook",
    ],
  },
  {
    id: 3,
    title: "System Architect",
    location: "Pune, India",
    company: "IBM",
    buttonText: "Details",
    date: "Aug 2019 - July 2022",
    icon: "work",
    color: "purple",
    hovercolor: "#90DCA0",
    description: [
      "Python",
      "SAP",
      "Networking",
      "Security",
      "IBM Cloud",
      "System Architecture",
    ],
  },
  {
    id: 4,
    title: "Web Developer Intern",
    location: "Pune, India",
    company: "SRV Media Pvt. Ltd.",
    buttonText: "Details",
    date: "May 2017 - July 2017",
    icon: "work",
    color: "orange",
    hovercolor: "#AB51DE",
    description: [
      "HTML",
      "CSS",
      "JavaScript",
      "Django",
      "PHP",
      "MySQL",
      "MongoDB",
      "SEO",
    ],
  },
];

export const educationTimelineItems = [
  {
    id: 1,
    title: "Master of Science in Computer Science",
    location: "Rochester, NY",
    school: "Rochester Institute of Technology",
    date: "Aug 2022 - May 2025",
    certification:
      "Advanced Certificate in Artificial Intelligence and Data Science",
    icon: "school",
    color: "orange",
    hovercolor: "#e37e2b",
    description: [
      "Artificial Intelligence",
      "Machine Learning",
      "Data Science",
      "NoSQL / NewSQL Databases",
      "Big Data Analytics",
      "Web Services and Service Oriented Computing",
    ],
  },
  {
    id: 2,
    title: "Bachelor of Technology in Information Technology",
    location: "Pune, India",
    school: "Symbiosis Institute of Technology",
    date: "Aug 2018 - May 2022",
    certification: "Diploma in Business Management",
    icon: "/assets/school.svg",
    hovercolor: "#5271CA",
    color: "blue",
    description: [
      "Data Structures",
      "Algorithms",
      "Operating Systems",
      "Database Management",
      "Software Development",
      "Computer Architecture",
    ],
  },
];
