const Technologies = {
  Angular: {
    id: 1,
    name: "Angular",
    path: "/assets/angular.png",
    documentation: "https://angular.io/docs",
  },
  Azure: {
    id: 2,
    name: "Azure",
    path: "/assets/azure.svg",
    documentation: "https://docs.microsoft.com/en-us/azure/",
  },
  CSharp: {
    id: 3,
    name: "C# .NET",
    path: "/assets/csharp.svg",
    documentation: "https://docs.microsoft.com/en-us/dotnet/",
  },
  Codeigniter: {
    id: 4,
    name: "CodeIgniter",
    path: "/assets/codeigniter.png",
    documentation: "https://codeigniter.com/user_guide/",
  },
  Convex: {
    id: 5,
    name: "Convex",
    path: "/assets/convex.svg",
    documentation: "https://convex.dev/docs",
  },
  Css: {
    id: 6,
    name: "CSS",
    path: "/assets/css.svg",
    documentation: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  Git: {
    id: 7,
    name: "Git",
    path: "/assets/github.svg",
    documentation: "https://git-scm.com/doc",
  },
  Html: {
    id: 8,
    name: "HTML",
    path: "/assets/html.svg",
    documentation: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  IbmCloud: {
    id: 9,
    name: "IBM Cloud",
    path: "/assets/cloud.svg",
    documentation: "https://www.ibm.com/cloud",
  },
  JavaScript: {
    id: 10,
    name: "JavaScript",
    path: "/assets/javascript.svg",
    documentation: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  Jupyter: {
    id: 11,
    name: "Jupyter Notebook",
    path: "/assets/jupyter.svg",
    documentation: "https://jupyter.org/documentation",
  },
  Linux: {
    id: 12,
    name: "Linux",
    path: "/assets/linux.png",
    documentation: "https://www.linux.org/docs/",
  },
  MongoDb: {
    id: 13,
    name: "MongoDB",
    path: "assets/mongo.png",
    documentation: "https://docs.mongodb.com/",
  },
  Networking: {
    id: 14,
    name: "Networking",
    path: "/assets/network.svg",
    documentation:
      "https://www.cisco.com/c/en/us/solutions/enterprise-networks/index.html",
  },
  Numpy: {
    id: 15,
    name: "Numpy",
    path: "/assets/numpy.svg",
    documentation: "https://numpy.org/doc/stable/",
  },
  Pandas: {
    id: 16,
    name: "Pandas",
    path: "/assets/pandas.png",
    documentation: "https://pandas.pydata.org/docs/",
  },
  Php: {
    id: 17,
    name: "PHP",
    path: "/assets/php.svg",
    documentation: "https://www.php.net/docs.php",
  },
  PostgreSql: {
    id: 18,
    name: "PostgreSQL",
    path: "/assets/postgresql.png",
    documentation: "https://www.postgresql.org/docs/",
  },
  Python: {
    id: 19,
    name: "Python",
    path: "/assets/python.png",
    documentation: "https://docs.python.org/3/",
  },
  Pygame: {
    id: 20,
    name: "PyGame",
    path: "assets/game.png",
    documentation: "https://www.pygame.org/docs/",
  },
  PyTorch: {
    id: 21,
    name: "PyTorch",
    path: "/assets/pytorch.svg",
    documentation: "https://pytorch.org/docs/stable/index.html",
  },
  React: {
    id: 22,
    name: "React.js",
    path: "/assets/react.svg",
    documentation: "https://react.dev/",
  },
  ResidenceAdvisor: {
    id: 23,
    name: "Residence Advisor",
    path: "/assets/leader.svg",
    documentation: "https://www.rit.edu/studentlife/resident-advisors",
  },
  RestApi: {
    id: 24,
    name: "REST API",
    path: "/assets/api.png",
    documentation: "https://restfulapi.net/",
  },
  Sap: {
    id: 25,
    name: "SAP",
    path: "/assets/sap.png",
    documentation: "https://help.sap.com/",
  },
  Security: {
    id: 26,
    name: "SAP Security",
    path: "/assets/security.svg",
    documentation: "https://www.sap.com/products/financial-management/grc.html",
  },
  Snowflake: {
    id: 27,
    name: "Snowflake",
    path: "/assets/snowflake.png",
    documentation: "https://docs.snowflake.com/en/",
  },
  Snort: {
    id: 28,
    name: "Snort",
    path: "assets/tools.svg",
    documentation: "https://www.snort.org/documents",
  },
  Sql: {
    id: 29,
    name: "SQL",
    path: "/assets/system.svg",
    documentation: "https://www.w3schools.com/sql/",
  },
  Suricata: {
    id: 30,
    name: "Suricata",
    path: "/assets/tools.svg",
    documentation: "https://suricata-ids.org/docs/",
  },
  SystemArchitecture: {
    id: 31,
    name: "System Architecture",
    path: "/assets/system.svg",
    documentation:
      "https://learning.sap.com/learning-journeys/introducing-sap-abap-platform-fundamentals/discussing-the-sap-three-tier-client-server-architecture",
  },
  Tailwind: {
    id: 32,
    name: "TailwindCSS",
    path: "assets/tailwindcss.png",
    documentation: "https://tailwindcss.com/docs/installation/using-vite",
  },
  TensorFlow: {
    id: 33,
    name: "TensorFlow",
    path: "/assets/tensorflow.svg",
    documentation: "https://www.tensorflow.org/guide",
  },
  TypeScript: {
    id: 34,
    name: "TypeScript",
    path: "/assets/typescript.png",
    documentation: "https://www.typescriptlang.org/docs/",
  },
};

export default Technologies;
