import Technologies from "./techstack";

const workExp = [
  {
    id: 1,
    title: "Full Stack Developer",
    location: "Saint Paul, MN",
    company: "Ecolab",
    duration: "Aug 2024 - Present",
    hovercolor: "#5271CA",
    spotlight: "/assets/spotlight2.png",
    technology: [
      Technologies.Angular,
      Technologies.TypeScript,
      Technologies.CSharp,
      Technologies.Snowflake,
      Technologies.Azure,
      Technologies.RestApi,
    ],
    responsibilities: [
      "Co-led feature development for Ecolab’s Institutional division solution penetration dashboard, improving data visualization for North American sales teams.",
      "Engineered reusable Angular components and interactive charts with Chart.js to enhance the Analytics dashboard.",
      "Optimized API endpoints using C# .NET Core, Azure Redis Caching, and LINQ for faster data retrieval.",
      "Improved Snowflake query performance by 20%, enabling seamless front-end integration.",
      "Conducted BDD QA testing with Microsoft Playwright and SpecFlow, ensuring high-quality deliverables.",
      "Authored unit tests using Karma to enhance application reliability.",
      "Collaborated in Agile sprints, contributing to retrospectives and sprint deliveries.",
      "Utilized Git, Azure Feature Manager, Redis Cache, and Application Insights for performance monitoring and optimization.",
    ],
  },
  {
    id: 2,
    title: "Machine Learning Course Assistant",
    location: "Rochester, NY",
    company: "Rochester Institute of Technology",
    duration: "August 2023-2024",
    hovercolor: "#e37e2b",
    spotlight: "/assets/spotlight1.png",
    technology: [
      Technologies.Python,
      Technologies.PyTorch,
      Technologies.TensorFlow,
      Technologies.Linux,
      Technologies.Git,
      Technologies.Jupyter,
    ],

    responsibilities: [
      "Supervising and conducting recitation sessions for graduate and undergraduate Introduction to Machine Learning courses.",
      "Grading assignments, programming homework, and projects for over 70 students.",
      "Mentoring and assisting students.",
      "Working collaboratively with the professor to cultivate a positive learning environment.",
    ],
  },
  {
    id: 3,
    title: "System Architect",
    location: "Pune, India",
    company: "IBM",
    duration: "August 2019 - July 2022",
    hovercolor: "#90DCA0",
    spotlight: "/assets/spotlight3.png",
    technology: [
      Technologies.Sap,
      Technologies.IbmCloud,
      Technologies.SystemArchitecture,
      Technologies.Python,
      Technologies.Networking,
      Technologies.Security,
    ],
    responsibilities: [
      "Recipienct of the IBM Service Excellence Award for outstanding performance towards delivering client value.",
      "Managed 9 SAP landscapes, including ECC, ERP and Solution Manager, ensuring smooth operation and optimal performance.",
      "Enhanced system security by 80% through a robust SAP Gateway security framework and Access Control Lists.",
      "Implemented Change and Transport Management System for change migration from sandbox to production with 0 downtime.",
      "Implemented Blueprism automation, reducing errors by 90% and saving 8 hours of manual effort using Python scripts.",
      "Led Gateway security management and SAP system upgrade projects, coordinating with clients and Kyndryl cloud teams to ensure successful execution and optimal performance. ",
    ],
  },
  {
    id: 4,
    title: "Graduate Residence Advisor (RA) & Service Desk Assistant",
    location: "Rochester, NY",
    company: "Rochester Institute of Technology",
    duration: "August 2022 - August 2024",
    hovercolor: "#e37e2b",
    spotlight: "/assets/spotlight1.png",
    technology: [Technologies.ResidenceAdvisor],
    responsibilities: [
      "One of the 12 Univeristy-wide Graduate Residence Advisors",
      "Recipient of the 2023-2024 RIT Residence Life Team Player and Community Builder Award.",
      "Provided mentorship and support to 400+ on campus apartment residents, fostering a positive and inclusive community.",
      "Organized and led 10+ community-building events, promoting student engagement and well-being.",
      "Served as front-line support to the residents, supporting them in celebration and in times of crisis and conflict.",
      "Managed and resolved resident conflicts and emergencies, ensuring a supportive and inclusive community.",
      "Collaborated with auxiliary services: Public Safety, Housing, Student Government, and Case Management to ensure a safe housing and college experience.",
      "As a Service Desk Assistant, provided administrative support to Residence Life staff, ensuring efficient operations and smooth workflow.",
    ],
  },
  {
    id: 5,
    title: "Web Developer Intern",
    location: "Pune, India",
    company: "SRV Media Pvt. Ltd.",
    duration: "May 2017 - July 2017",
    hovercolor: "#AB51DE",
    spotlight: "/assets/spotlight5.png",
    technology: [
      Technologies.Php,
      Technologies.Codeigniter,
      Technologies.Html,
      Technologies.Css,
      Technologies.JavaScript,
      Technologies.Sql,
      Technologies.Python,
    ],
    responsibilities: [
      "Developed the frontend for a content aggregation website prototype using HTML, CSS, JavaScript, and the CodeIgniter Framework following the standard software development cycle and Agile methodology.",
      "Implemented SEO best practices to improve website ranking and visibility.",
      "Designed and implemented the backend architecture for the prototype using PHP, SQL, Bootstrap, and the CodeIgniter Framework.",
      "Collaborated with the development and UI/UX team to ensure seamless integration of frontend and backend functionalities.",
    ],
  },
];

export default workExp;
